### PR TITLE
Updates pricing on home page

### PR DESCRIPTION
**Pull request by asc313x**
Molly decided that she'd like to make a pricing change. This felt like the easiest way to do it quickly. I created a new button that's at `/books` through the Statamic edit interface. Placed the same ID here so that the pricing is consistent.

### CODE REVIEW

**Comment by asc313x** [comment]
@kungfukoala I know we talked about deploying, but I haven't closed the loop on that. Can you push this live for today? I'll try to make an effort this weekend (too cold to camp now) at getting that sorted.

**Comment by kungfukoala** [comment]
No problem.

**Comment by asc313x** [comment]
:+1: :raised_hands:

**Comment by kungfukoala** [comment]
:+1: done

**Pull request merged**
